version: '3'

services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    command: -p 5433
    expose:
      - 5433
    volumes:
      - ./docker/init-multi-postgres-databases.sh:/docker-entrypoint-initdb.d/init-multi-postgres-databases.sh


  redis:
    image: redis
    restart: always
    command: --port 6380
    expose:
      - 6380
    env_file:
      - .env

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: lonely_eye
    command: ["/lonely-eye/docker/app.sh"]
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis