version: '3'

services:
  postgres:
    image: postgres
    restart: always
    command: -p 5433
    expose:
      - 5432
    env_file:
      - .env-prod


  redis:
    image: redis
    restart: always
    command: --port 6380
    expose:
      - 6380
    env_file:
      - .env-prod

  app:
    build:
      context: .
    env_file:
      - .env-prod
    container_name: lonely_eye
    command: ["/lonely-eye/docker/app.sh"]
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis