"""Add column skill in table 'solution'

Revision ID: 96f7182e50d5
Revises: 104ec5fee94a
Create Date: 2024-03-20 05:58:25.997845

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "96f7182e50d5"
down_revision: Union[str, None] = "104ec5fee94a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("solution", sa.Column("skill", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("solution", "skill")
    # ### end Alembic commands ###
